### PR TITLE
fix issue #52: render pathways in client

### LINKED ISSUE #52: Cannot Render Pathways in Client
The Pathway display page gets a 400 from the GraphQL API because of this error: 
```json 
{
    "errors": [
        {
            "message": "Cannot query field \"isPathway\" on type \"Step\". Did you mean \"pathway\"?",
            "locations": [
                {
                    "line": 10,
                    "column": 7
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Cannot query field \"isPathway\" on type \"Step\". Did you mean \"pathway\"?",
                        "    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
                        "    at Object.enter (/app/node_modules/graphql/language/visitor.js:324:29)",
                        "    at Object.enter (/app/node_modules/graphql/language/visitor.js:375:25)",
                        "    at visit (/app/node_modules/graphql/language/visitor.js:242:26)",
                        "    at Object.validate (/app/node_modules/graphql/validation/validate.js:73:24)",
                        "    at validate (/app/node_modules/apollo-server-core/dist/requestPipeline.js:221:34)",
                        "    at Object.<anonymous> (/app/node_modules/apollo-server-core/dist/requestPipeline.js:118:42)",
                        "    at Generator.next (<anonymous>)",
                        "    at fulfilled (/app/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
                    ]
                }
            }
        }
    ]
}
```

This is happening because the `Step` GraphQL Schema got changed to this:

```graphql
type Step {
    id: String
    name: String
    time: Int
    index: Int
    stepType: StepType
    pathway: Pathway @relation(name: "INCLUDES", direction: "OUT")
    content: Content @relation(name: "INCLUDES", direction: "OUT")
    userStatus: StepStatus
}
```

Update the request on the client side to fix this.

### PR DESCRIPTION
**Pull request by psrth**
updated the request in **GetPathway** component in client after change in `Step` GraphQL schema — pathways are now rendering fine.

### CODE REVIEW

File: client/src/components/GetPathway/GetPathway.js [hunk 1]
```diff
@@ -21,15 +21,14 @@ const GetPathway = (props) => {
                     name
                     time
                     index
-                    isPathway
+                    pathway{
+                        name
```
Comment (hedonhermdev) [inline client/src/components/GetPathway/GetPathway.js:26]: You'll probably need the pathway id too to render the other pathway or get the link to that pathway. Request both `name` and `id` of pathway.

**Review by hedonhermdev — CHANGES_REQUESTED** [review]

File: client/src/components/GetPathway/GetPathway.js (hunk 1 above)
Comment (psrth) [reply client/src/components/GetPathway/GetPathway.js:26]: right, my bad — have made the change.

**Review by hedonhermdev — APPROVED** [review]
LGTM!
